apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
---
