apiVersion: v1
kind: Service
metadata:
  name: istio-egressgateway
  labels:
    app: istio-egressgateway
    istio: egressgateway
spec:
  ports:
  # Any ports exposed in Gateway resources should be exposed here.
  - name: http2
    port: 80
  - name: https
    port: 443
  selector:
    istio: egressgateway
    app: istio-egressgateway
