apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgenerator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendationservice
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cart
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice