apiVersion: networking.gke.io/v1beta1
kind: MultiClusterIngress
metadata:
  name: frontend-multi-cluster-ingress
  namespace: bank-of-anthos
spec:
  template:
    spec:
      backend:
       serviceName: frontend-multi-cluster-service
       servicePort: 80
