# [START servicemesh_cloud_trace_sampling]
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
  values:
    pilot:
      traceSampling: 100
    global:
       proxy:
         tracer: stackdriver
# [END servicemesh_cloud_trace_sampling]
