# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: frontend
spec:
  workloadSelector:
    labels:
      app: frontend
  egress:
  - hosts:
    - istio-system/*
    - ./adservice.default.svc.cluster.local
    - ./cartservice.default.svc.cluster.local
    - ./checkoutservice.default.svc.cluster.local
    - ./currencyservice.default.svc.cluster.local
    - ./productcatalogservice.default.svc.cluster.local
    - ./recommendationservice.default.svc.cluster.local
    - ./shippingservice.default.svc.cluster.local