# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START servicemesh_sidecars_for_namespace_kustomization_component]
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJson6902:
- target:
    kind: Sidecar
    name: cartservice
  patch: |-
    - op: replace
      path: /spec/egress/0/hosts
      value:
        - istio-system/*
        - ./redis-cart.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
- target:
    kind: Sidecar
    name: checkoutservice
  patch: |-
    - op: replace
      path: /spec/egress/0/hosts
      value:
        - istio-system/*
        - ./cartservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./currencyservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./emailservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./paymentservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./productcatalogservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./shippingservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
- target:
    kind: Sidecar
    name: frontend
  patch: |-
    - op: replace
      path: /spec/egress/0/hosts
      value:
        - istio-system/*
        - ./adservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./cartservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./checkoutservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./currencyservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./productcatalogservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./recommendationservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
        - ./shippingservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
- target:
    kind: Sidecar
    name: loadgenerator
  patch: |-
    - op: replace
      path: /spec/egress/0/hosts
      value:
        - istio-system/*
        - ./frontend.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
- target:
    kind: Sidecar
    name: recommendationservice
  patch: |-
    - op: replace
      path: /spec/egress/0/hosts
      value:
        - istio-system/*
        - ./productcatalogservice.ONLINEBOUTIQUE_NAMESPACE.svc.cluster.local
# [END servicemesh_sidecars_for_namespace_kustomization_component]