apiVersion: v1
kind: ServiceAccount
metadata:
  name: ledger-db
  namespace: bank-of-anthos
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ledger-db
  namespace: bank-of-anthos
spec:
  serviceName: "ledger-db"
  replicas: 1
  selector:
    matchLabels:
      app: ledger-db
  template:
    metadata:
      labels:
        app: ledger-db
    spec:
      serviceAccountName: ledger-db
      containers:
        - name: postgres
          image: gcr.io/bank-of-anthos-ci/ledger-db:v0.5.4
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: ledger-db-config
            - configMapRef:
                name: demo-data-config
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgresdb
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-db-config
  namespace: bank-of-anthos
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
  SPRING_DATASOURCE_USERNAME: admin # should match POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: password # should match POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-db
  namespace: bank-of-anthos
spec:
  type: ClusterIP
  selector:
    app: ledger-db
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432