# [START servicemesh_asmgcp_profile]
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    egressGateways:
    - enabled: true
      k8s:
        env:
        - name: CA_ADDR
          value: meshca.googleapis.com:443
# [END servicemesh_asmgcp_profile]
