# [START servicemesh_asmmulticloud_profile]
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
# [END servicemesh_asmmulticloud_profile]
