apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: ONLINEBOUTIQUE_NAMESPACE
        labels:
          istio.io/rev: ASM_VERSION