name: asm-mcp-multi-clusters-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/asm-mcp-multi-clusters-ci.yml'
      - 'demos/asm-mcp-multi-clusters/terraform/**'
  pull_request:
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build whereami container
        run: |
          cd demos/asm-mcp-multi-clusters/terraform
          terraform init -backend=false
          terraform validate
